on: [workflow_dispatch]
name: Build
jobs:
  android-release-build:
    name: android-release-build
    runs-on: ubuntu-latest
    container: ghcr.io/niklaslehnfeld/flutter-essentials-docker:master
    steps:
      - uses: actions/checkout@v3
      - uses: NiklasLehnfeld/flutter-android-build-action@v1
        id: android-build
        with:
          release: false
      - name: Archive APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: ${{ steps.android-build.outputs.apk-path }}

  create-github-release:
    name: create-github-release
    runs-on: ubuntu-latest
    needs: [android-release-build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: release-apk
      - id: version
        uses: NiklasLehnfeld/flutter-version-number-action@v1
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: ${{ steps.version.outputs.version-number }}
          title: ${{ steps.version.outputs.version-number }}
          files: |
            *.apk



